#!/bin/bash

# Enable the JupyterLab extension
jupyter labextension enable @jovyanai/labextension

# Create the JupyterLab settings directory if it doesn't exist
mkdir -p ~/.jupyter/lab/user-settings/@jovyanai/labextension/

# Copy the starter notebook to the home directory
cp binder/starter-notebook.ipynb ${HOME}/starter-notebook.ipynb
cp binder/sample_data ${HOME}/sample_data
cp binder/.env ${HOME}/.env

WORKSPACE_DIR=${HOME}

# Set up JupyterLab workspace
mkdir -p ${HOME}/.jupyter/lab/workspaces
cat << EOF > ${HOME}/.jupyter/lab/workspaces/default-workspace.json
{
  "data": {
    "layout-restorer:data": {
      "main": {
        "dock": {
          "type": "tab-area",
          "currentIndex": 0,
          "widgets": ["notebook:starter-notebook.ipynb"]
        }
      },
      "left": {
        "collapsed": false,
        "current": "jovyanai-panel",
        "widgets": ["jovyanai-panel"]
      }
    }
  }
}
EOF 