name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual trigger

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    name: Build and Deploy Docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Or your preferred Python version
          cache: 'pip' # Cache pip dependencies

      - name: Install uv
        run: pip install uv

      - name: Install project dependencies (including dev)
        run: uv sync

      - name: Build Jupyter Book
        run: jupyter-book build jovyan-doc

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire directory
          path: 'jovyan-doc/_build/html'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 